#!/bin/sh

# MIT License
#
# Copyright (c) 2025 Alexey Gumirov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# For yt-dlp to work correctly with cookies and being able to pull the title from the YouTube video
# you need to pass you browser profile directory to the script (for Chrome/Chromium or Firefox)
# More details on the yt-dlp documentation page: https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#filesystem-options
BROWSER_PROFILE="firefox:abc123def.default-release"
MPV_SOCKET="/tmp/mpv_socket"
MPV_CONTROL_SCRIPT="$(dirname "$0")/mpv-control"

notification(){
    notify-send "Playing YT:" "${1} ☕️🎶"
}

player_launch(){
    notification "${2}"
    mpv --quiet --input-ipc-server="${MPV_SOCKET}" "${1}" &
}

main() {
    url=$(rofi -dmenu -font "$FONT" -yoffset 24 -no-fixed-num-lines -p "url" -theme Paper)
    if [ -z "$url" ]; then
        exit 0
    fi
    url=$(printf "%s" "$url" | cut -d'&' -f1)
    title=$(yt-dlp --cookies-from-browser "$BROWSER_PROFILE" --get-title "$url")
    "${MPV_CONTROL_SCRIPT}" -quit
    player_launch "${url}" "${title}"
}

main
